name: Pull Request

on:
  pull_request:
    branches: [main]

env:
  WORKING_DIRECTORY: 'packages/bot-service'

jobs:
  pull_requests:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ env.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: ${{ github.workspace }}/${{ env.WORKING_DIRECTORY }}
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test